version: '3'
services:
  express-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: n-app
    container_name: n-app
    tty: true
    ports:
      - 4000:3000
    volumes:
      - ./app:/home/app/src
